name: Frontend App Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - "src/frontend/**"
  workflow_dispatch: # allows manual execution through GH CLI, API or browser interface

jobs:
  buildFront:
    name: "Build Frontend"
    runs-on: ubuntu-latest

#Checkout
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
#Log into azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy
      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{secrets.AZURE_SUBSCRIPTION}}
          resourceGroupName: ${{secrets.AZURE_RG}}
          template: ../infra/main.bicep
          parameters: 'storagePrefix:cs41003200202a8cc09 storageSKU:Standard_LRS'
          failOnStdErr: false
 