name: Deploy API 
env: 
  DOTNET_VERSION: "5.0"
on:
  push:
    branches:
      - main
    paths: 
      - .src/backend/api
  workflow_dispatch: # allows manual execution through GH CLI, API or browser interface

jobs:
  buildAPI:
    name: "Build API"
    runs-on: ubuntu-latest
#Checkout
    steps:
      - uses: actions/checkout@v2
#Set up .NET core
      - name: Setup .NET Core 
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: 'dotnet build'  
        shell: bash
        run: |
          cd src/backend/api/
          dotnet restore
          dotnet build --configuration Release
      - name: 'dotnet publish'
        shell: bash
        run: |
          cd src/backend/api/
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myAPI

#Upload artifacts
      - name: 'Upload API artifact'
        uses: actions/upload-artifact@v2
        with:
          name: APIApp
          path: ${{env.DOTNET_ROOT}}/myAPI
          if-no-files-found: error
          retention-days: 5
#Download artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v2
#Deploy
      - name: Deploy API to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hackerTruongAPI'
          publish-profile: ${{secrets.AZURE_API_PUBLISHPROFILE}}
          package: ./APIApp
 