name: Deploy Bicep template
on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual execution through GH CLI, API or browser interface

jobs:
  buildBicep:
    name: "Deploy Bicep"
    runs-on: ubuntu-latest
#Checkout
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
#Log into azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
#Deploy
      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{secrets.AZURE_SUBSCRIPTION}}
          resourceGroupName: ${{secrets.AZURE_RG}}
          template: ./infra/main.bicep
          failOnStdErr: false
      - name: logout
        run: |
          az logout