name: Deploy API 
env: 
  DOTNET_VERSION: "5.0.x"
on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual execution through GH CLI, API or browser interface

jobs:
  buildAPI:
    name: "Build API"
    runs-on: ubuntu-latest
    
#Checkout
    steps:
      - uses: actions/checkout@main

#Set up .NET core
      - name: Setup .NET Core 
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: 'dotnet build'  
        shell: bash
        run: |
          cd src/backend/api
          dotnet restore
          dotnet build --configuration Release
      - name: 'dotnet publish'
        shell: bash
        run: |
          cd src/backend/api
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myAPI

#Upload artifacts
      - name: 'Upload API artifact'
        uses: actions/upload-artifact@v2
        with:
          name: APIApp
          path: ${{env.DOTNET_ROOT}}/myAPI
          if-no-files-found: error
          retention-days: 30

#Download artifacts
  deployAPI: 
    name: Deploy API
    runs-on: ubuntu-latest
    needs: buildAPI 
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2

#Log into azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
#Deploy
    - name: Deploy API to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hackathon-truongsahay-api'
        package: ./APIApp

 
