name: Deploy Frontend 
on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual execution through GH CLI, API or browser interface

jobs:
  buildFront:
    name: "Build Frontend"
    runs-on: ubuntu-latest
#Checkout
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
#Set up node
      - name: Node Setup 
        uses: actions/setup-node@v2
        with: 
          node-version: '14.x'
      - name: 'npm install, build and test'
        run: |
          npm install
          npm install --global yarn
          npm run build --if-present
          npm run test --if-present
        working-directory: ./src/frontend
#Upload artifacts
      - name: 'Upload artifact for deployment job'
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./src/frontend/build
          if-no-files-found: error
          retention-days: 5
#Download artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: node-app
#Deploy
      - name: Deploy Frontend to Azure WebApp
        uses: azure/webapps-deploy@v1
        with:
          app-name: 'hackerTruong588'
          publish-profile: ${{secrets.AZURE_PUBLISHPROFILE}}
          package: ./src/frontend
 